version: '3.8'
services:
  mysql:
    image: mysql:8.0
    # ...
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  application:
    # ...
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started # Redis는 healthcheck가 간단하지 않으므로 started로 두거나 별도 스크립트 필요